### ISSUE TITLE
Twitter authentication still requires name and email

### ISSUE THREAD

**Issue by Vernal** [postmatic/social#1]
Authentication with Twitter works fine, but when submitting a comment I get an error that name and email are missing:
![screen shot 2015-09-06 at 9 22 47 pm](https://cloud.githubusercontent.com/assets/80932/9707684/6eff97e0-54dd-11e5-97ee-0b8a914ad0c0.png)

**Comment by filkaris** [comment]
The problem is that the email is still not fetched (the username is filled in properly).
This also relates to #3 

I added the extra parameter in the oauth GET call but it seems that your app will have to get whitelisted first.

![screenshot from 2015-09-13 22 12 30](https://cloud.githubusercontent.com/assets/1624978/9838364/ada4d12c-5a64-11e5-8c58-9d9b54ebd1d4.png)

More info here https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by Vernal** [comment]
Closing. See #13
