### ISSUE TITLE
Comment form is repeating when replying to a comment

### ISSUE THREAD

**Issue by Vernal** [postmatic/social#21]
Hey @filkaris check out this weird thing:
http://quick.as/wJZU35GV

Thoughts?

**Comment by filkaris** [comment]
Is this happening just with G+ or with other networks as well?

**Comment by Vernal** [comment]
With any.

**Comment by Vernal** [comment]
Hey @filkaris ... going to have a friend look at this one. Don't worry about it for now.

**Comment by filkaris** [comment]
Ok @Vernal , no problem.

@ronalfy Take a look at js/ixwp-comments-social-login.js
On line 22 we populate the #ixwp-social-comment-wrapper div with data from PHP.
The data comes from functions/Ixwp_{network}_Authenticator.php > comment_form().
For example in functions/Ixwp_Gplus_Authenticator.php it's on line 115.

That's the approach used by the plugin creators. Either we keep this and use the correct div instead or we try a new approach to display the new form in order to avoid recursion.

**Comment by Vernal** [comment]
Hey @filkaris Thanks for the tip. I'm pretty certain that this bug was present in the original plugin so I wasn't crazy about asking you to fix it out of spec. Plus I know how busy you are :)

**Comment by ronalfy** [comment]
Fixed with https://github.com/postmatic/social/commit/8a5bc6e3e981f123f8d7a2812595fa31a90e7cde
