### ISSUE TITLE
Epoch / Postmatic Compatibility

### ISSUE THREAD

**Issue by ronalfy** [postmatic/social#41]
If you can have Dylan take a look, would be much appreciated. I don't want to open that can of worms myself.

**Comment by cyberhobo** [comment]
Are there any known incompatibilities to start with?

**Comment by Vernal** [comment]
Hey Dylan,
Yea here are the notes:

When you connect with either facebook or twitter we hide the native Postmatic _Participate in this conversation via email_ box and instead show our own.
If the user checks the box, it then asks them for which email address they want to use (since we can't get one from twitter, and don't always get clean ones from facebook).
This works fine with epoch off, but with epoch on it bombs. Could be an enqueue problem?

It's up and running on qa.pond now. 

![deserunt_rerum_qui_eligendi_id___postmatic_sandbox](https://cloud.githubusercontent.com/assets/80932/10913506/38baca1c-821c-11e5-8c1e-111eaf2fb246.png)

**Comment by ronalfy** [comment]
https://github.com/postmatic/postmatic-social/commit/c4a717f0da9d24aec7e1b761171f576a0a077f7a

Fixed. Remove if Facebook or Twitter is detected.
